import Header from "@/components/Header";
import "@/app/globals.css";
import "@/app/themes.css";
import { twMerge } from "tailwind-merge";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={twMerge("theme-default bg-default")}>
        <Header />
        {children}
      </body>
    </html>
  );
}
